### ISSUE TITLE
Multi Episode Download Missing x.x0

### ISSUE THREAD

**Issue by jeffwrusso** [KevCui/soap2day-dl#2] opened 2021-03-20 00:29 UTC
Just noticed when using an episode download range the episodes ending in 0 are missing from the downloads.  For example if you use -e 1.1-1.51 you will be missing 1.10,1.20,1.30,1.40,1.50.  I have not been able to test if it makes a difference if the the last digit in the range is a 0 if it makes a difference (example 1.1-1.50).

Thanks!

**Comment by KevCui** [comment] 2021-03-20 12:37
Hi @jeffwrusso, good catch. The issue is fixed in the latest commit. Thanks.

**Closed** 2021-03-20 12:36 UTC
Labels: bug
