### ISSUE TITLE
Downloading more that 7 Episodes Error

### ISSUE THREAD

**Issue by jeffwrusso** [KevCui/soap2day-dl#1] opened 2021-03-18 18:44 UTC
Great work!  I noticed something after I got this up and running on a Ubuntu laptop.

If you download more than 7 episode you get an error message stating:
parse error: Invalid numeric literal at line 1, column 10

**Comment by KevCui** [comment] 2021-03-18 19:48
Hi @jeffwrusso, what's the TV series name you were downloading? Which episodes? If you would like to share those info, it will help me for the further debugging.

**Comment by KevCui** [comment] 2021-03-18 21:22
Ok, I find the root cause. It should be fixed in the latest commit.

**Closed** 2021-03-18 21:21 UTC
Labels: question
