### ISSUE TITLE
Wait a few seconds for fetching cookie...

### ISSUE THREAD

**Issue by azeekhan1** [KevCui/soap2day-dl#21] opened 2022-07-30 20:57 UTC
Hello, Can i run this on ubuntu VPS or is it for Windows? Sorry I am a newbie and trying to set up this amazing script. I tried running on ubunut and i am getting "Wait a few seconds for fetching cookie..." when I type ./soap2day-dl.sh -p /tv_aTo2Mjs.html and nothing happens.

**Comment by KevCui** [comment] 2022-07-31 11:21
Hey @azeekhan1, the script should work on Ubuntu. You could run the command with the flag `-d` to see more logs. Let me know if you saw any errors in the logs.

**Comment by KevCui** [comment] 2022-08-19 12:28
Hey @azeekhan1, there are other ones having the same issue on Ubuntu VPS. Therefore, I'm closing this issue as duplicate of #22, due to the discussions already involved many people there. If you have more details to share, please feel free to leave comments in #22.

**Closed by KevCui** 2022-08-19 12:28 UTC
